#!/bin/bash
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j2140' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j2140' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j2140' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j2116' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j2116' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j2116' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j1613' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j1613' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j1613' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j1558' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j1558' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j1558' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j1506' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j1506' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j1506' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j1341' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j1341' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j1341' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j1219' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j1219' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j1219' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j1107' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j1107' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j1107' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j0944' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j0944' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j0944' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j0905' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j0905' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j0905' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j0901' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j0901' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j0901' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='ssp' --galaxy='j0826' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='delayed-tau' --galaxy='j0826' --sedfit  --verbose 
python bgl_sedfit.py --nproc=4 --priors='bursty' --galaxy='j0826' --sedfit  --verbose 
